

CREATE DATABASE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE		
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
	
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE));


INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','254678978965874');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOS@IG.COM','654678978115874');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','154678978963174');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'335465789789674');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','854678978555874');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F','CELIA@IG.COM','95467897891234');





INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONO SA','CENTRO','B.HORIZONTE','MG',4 );
INSERT INTO ENDERECO VALUES(NULL, 'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO', 'RJ',1 );
INSERT INTO ENDERECO VALUES(NULL, 'RUA PRESIDENTE VARGAS','JARDINS','SAO PAULO', 'SP',3 );
INSERT INTO ENDERECO VALUES(NULL, 'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO', 'RJ',5 );
INSERT INTO ENDERECO VALUES(NULL, 'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',2 );
INSERT INTO ENDERECO VALUES(NULL, 'RUA URUGUAIANA','CENTRO','VITORIA','ES',6 );



INSERT INTO TELEFONE VALUES(NULL,'CEL','95568745',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','955535',5);
INSERT INTO TELEFONE VALUES(NULL,'COM','95567745',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','95123745',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','9559779745',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','95566635',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','55568745',3);